name: plant_disease_recognition
description: "A new Flutter project."
publish_to: 'none' # This line prevents accidental publishing to pub.dev
version: 1.0.0+1
environment:
  sdk: '>=3.3.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  image_picker: ^1.1.0
  camera: ^0.10.5+9
  flutter_vlc_player: ^7.4.1
  url_launcher: ^6.1.5
  webview_flutter: ^4.7.0
  firebase_core: ^2.30.1
  cloud_firestore: ^4.17.2
  firebase_storage: ^11.7.4
  firebase_messaging: ^14.9.1
  firebase_auth: ^4.19.4
  google_sign_in: ^6.2.1
  awesome_dialog: ^3.2.1
  firebase_app_check: ^0.2.2+5
  flutter_facebook_auth: ^3.5.0
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
