// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCjpi-MPKuRybJ9VyXPIXlG3spqPglR8HQ',
    appId: '1:937336425153:web:01e67fa9955a815c16a240',
    messagingSenderId: '937336425153',
    projectId: 'appbackend-23cd6',
    authDomain: 'appbackend-23cd6.firebaseapp.com',
    storageBucket: 'appbackend-23cd6.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBlbHbACPb1lUutnS7ZSMSctgtwKqv_RNg',
    appId: '1:937336425153:android:d13076db39ff6c5b16a240',
    messagingSenderId: '937336425153',
    projectId: 'appbackend-23cd6',
    storageBucket: 'appbackend-23cd6.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD6JlLunQOfRB_LpRdycjX1_0oGso4I-9M',
    appId: '1:937336425153:ios:908aef401610bd1216a240',
    messagingSenderId: '937336425153',
    projectId: 'appbackend-23cd6',
    storageBucket: 'appbackend-23cd6.appspot.com',
    iosBundleId: 'com.example.plantDiseaseRecognition',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD6JlLunQOfRB_LpRdycjX1_0oGso4I-9M',
    appId: '1:937336425153:ios:908aef401610bd1216a240',
    messagingSenderId: '937336425153',
    projectId: 'appbackend-23cd6',
    storageBucket: 'appbackend-23cd6.appspot.com',
    iosBundleId: 'com.example.plantDiseaseRecognition',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCjpi-MPKuRybJ9VyXPIXlG3spqPglR8HQ',
    appId: '1:937336425153:web:e4316b8ab274b8a116a240',
    messagingSenderId: '937336425153',
    projectId: 'appbackend-23cd6',
    authDomain: 'appbackend-23cd6.firebaseapp.com',
    storageBucket: 'appbackend-23cd6.appspot.com',
  );
}
